version: '3.4'

services:
  nodejs:
    build:
      context: ./dockerdev/node
      dockerfile: Dockerfile
      target: nodejs
    image: node:14-alpine
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - ${NODE_PORT}:4001
    links:
      - db
      - postgres
    networks:
      backend:
        ipv4_address: ${GA_NODE_IP}
    command: >
       bash -c "sleep infinity"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      DATABASE_URL2: ${DATABASE_URL2}

  db:
    image: mysql:5.7
    restart: always
    volumes:
      - ./todo-mysql-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    command: [ "mysqld", "--bind-address=0.0.0.0",
               "--character-set-server=utf8mb4",
               "--collation-server=utf8mb4_unicode_ci",
    ]
    networks:
      backend:
        ipv4_address: ${GA_DB_HOST}

  postgres:
    image: kartoza/postgis:11.0-2.5
    ports:
      - ${DB_PORT_PG}:5432
    volumes:
      - ./todo-pgsql-data:/var/lib/postgresql
    environment:
      # If you need to create multiple database you can add coma separated databases eg gis,data
      - POSTGRES_DBNAME=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASS=${DB_PASS}
      - "ALLOW_IP_RANGE=0.0.0.0/0"
      # Add extensions you need to be enabled by default in the DB. Default are the three specified below
      - "POSTGRES_MULTIPLE_EXTENSIONS=${POSTGRES_MULTIPLE_EXTENSIONS:-postgis,hstore,postgis_topology}"
      - "FORCE_SSL=TRUE"
      - "DEFAULT_ENCODING=UTF8"
    networks:
      backend:
        ipv4_address: ${GA_DB_HOST2}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${PHP_MYADMIN_PORT}:80
    links:
      # for mysql container
      - db:db

networks:
  backend:
    ipam:
      config:
        - subnet: ${GA_BACKEND_SUBNET}
