{
    listarAeropuertos {
        id
        localizacion
        aviones {
            id
            velocidadHora
            pasajeros {
                nombre
                apellido
            }
        }
    }
}
